export const SHARED_EMITTER = 'SHARED_EMITTER';
export const POST_COMMENT = 'POST_COMMENT';
export const GET_POST_COMMENT = 'GET_POST_COMMENT';
export const GET_POST_COMMENT_COUNT = 'GET_POST_COMMENT_COUNT';
export const GET_POST_REACTIONS = 'GET_POST_REACTIONS';
export const GET_POST_VIEWS = 'GET_POST_VIEWS';
export const GET_REPOST_COUNTS = 'GET_REPOST_COUNTS';
export const GET_QOUTE_COUNTS = 'GET_QOUTE_COUNTS';
export const GET_COMMENT_VIEWS = 'GET_COMMENT_VIEWS';
export const GET_FEEDS = 'GET_FEEDS';
export const GET_DELETED_POST = 'GET_DELETED_POST';
export const GET_DELETED_FEED = 'GET_DELETED_FEED';

// Events for chat service
export const GET_GROUP_MESSAGE = 'GET_GROUP_MESSAGE';
export const GET_PRIVATE_MESSAGE = 'GET_PRIVATE_MESSAGE';
export const GET_CHAT_UPDATED = 'GET_CHAT_UPDATED';
export const CHAT_DELETED = 'CHAT_DELETED';
export const GET_GROUP_INVITATION = 'GET_GROUP_INVITATION';
export const GET_ACCEPT_INVITATION = 'GET_ACCEPT_INVITATION';
export const GET_GRUOP_UPDATED = 'GET_GRUOP_UPDATED';
export const TYPING_MESSAGE = 'TYPING_MESSAGE';
export const SET_REMOVE_FROM_GROUP = 'SET_REMOVE_FROM_GROUP';
export const SET_LEAVE_GROUP = 'SET_LEAVE_GROUP';
export const SET_CLOSE_GROUP = 'SET_CLOSE_GROUP';
export const SET_MESSAGE_DELETED = 'SET_MESSAGE_DELETED';
export const GET_MESSAGE_SEEN = 'GET_MESSAGE_SEEN';
export const SET_MESSAGE_SEEN = 'SET_MESSAGE_SEEN';

export const GET_GROUP_MESSAGE_NOTIFICATION = 'GET_GROUP_MESSAGE_NOTIFICATION';
export const GET_PRIVATE_MESSAGE_NOTIFICATION =
    'GET_PRIVATE_MESSAGE_NOTIFICATION';
export const GET_MESSAGE_SEEN_NOTIFICATION = 'GET_MESSAGE_SEEN_NOTIFICATION';
// Events for landmap service
export const GET_ISLAND = 'GET_ISLAND';
export const GET_MRLANDS = 'GET_MRLANDS';

export const USER_UPDATED = 'USER_UPDATED';

// scores
export const GET_MONTH_SCORERES = 'GET_MONTH_SCORERES';

// collections
export const GET_COLLECTIONS_UPDATE = 'GET_COLLECTIONS_UPDATE';
export const GET_COLLECTION_VIEWS = 'GET_COLLECTION_VIEWS';

export const EMIT_RECENT_ACTIVITIES = 'EMIT_RECENT_ACTIVITIES';

export const LOGOUT_FROM_ADMIN = 'LOGOUT_FROM_ADMIN';
